site_url: https://easx-community.github.io/easx-docs/
site_name: EASX Documentation Develop Branch
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Overview: Overview.md
  - Getting Started: Getting-Started.md
  - How To Connect: How-To-Connect.md
  - Subscriptions Participants: Subscriptions--Participants.md
  - APIs: APIs.md
  - EAS Client:
      - Introduction: EAS-Client/Introduction.md
      - Settings: EAS-Client/Settings.md
      - Commands: EAS-Client/Commands.md
      - Deploy To Azure: EAS-Client/Deploy-To-Azure.md
      - System Requirements: EAS-Client/System-Requirements.md
      - Changelog: EAS-Client/Changelog.md
